<template>
    <div class="split"></div>
</template>

<script>
export default {
  name: 'ratings',
  data () {
    return {
      
    }
  }
}
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped lang="stylus">
    .split
        width 100%
        height 16px
        border-top 1px solid rgba(7,17,27,0.1)
        border-bottom 1px solid rgba(7,17,27,0.1)
        background #f3f5f7
</style>
